name: search

on:
  workflow_dispatch:


env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  TOKEN: ${{ secrets.TOKEN }}
  HEADLESS: ${{ secrets.HEADLESS }}
  URL_STAGE: ${{ secrets.URL_STAGE }}


jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: tests
        run: pytest tests/internet/search
        continue-on-error: true